[colors.primary]
background = '#11140e'
foreground = '#e1e4d9'
 
[colors.cursor]
text = '#e1e4d9'
cursor = '#c4c8bb' 
 
[colors.vi_mode_cursor]
text = '#11140e'
cursor = '#acd28f' 
 
[colors.search.matches]
foreground = '#44483e' 
background = '#a0cfce' 
 
[colors.search.focused_match]
foreground = '#44483e' 
background = '#acd28f' 
 
[colors.footer_bar]
foreground = '#44483e' 
background = '#e1e4d9' 
 
[colors.hints.start]
foreground = '#44483e' 
background = '#bdcbaf' 
 
[colors.hints.end]
foreground = '#44483e' 
background = '#bdcbaf' 
 
[colors.selection]
text = '#11140e'
background = '#acd28f'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#acd28f' 
yellow = '#476730' 
blue = '#acd28f' 
magenta = '#a0cfce' 
cyan = '#bdcbaf' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
